const actionTypes = {
  SET_PLAYER: "SET_PLAYER",
  RESET_PLAYER: "RESET_PLAYER",

  SET_PLAYER_BOARD: "SET_PLAYER_BOARD",
  UPDATE_PLAYER_BOARD: "UPDATE_PLAYER_BOARD",
  DELETE_PLAYER_BOARD: "DELETE_PLAYER_BOARD",

  SET_PLAYER_SHIPS: "SET_PLAYER_SHIPS",
  UPDATE_PLAYER_SHIPS: "UPDATE_PLAYER_SHIPS",
  DELETE_PLAYER_SHIPS: "DELETE_PLAYER_SHIPS",

  SET_BOT_BOARD: "SET_BOT_BOARD",
  UPDATE_BOT_BOARD: "UPDATE_BOT_BOARD",
  DELETE_BOT_BOARD: "DELETE_BOT_BOARD",

  SET_BOT_SHIPS: "SET_BOT_SHIPS",
  UPDATE_BOT_SHIPS: "UPDATE_BOT_SHIPS",
  DELETE_BOT_SHIPS: "DELETE_BOT_SHIPS",

  OPEN_DIALOG: "OPEN_DIALOG",
  CLOSE_DIALOG: "CLOSE_DIALOG",
};

export default actionTypes;