const actionTypes = {
  SET_PLAYER: "SET_PLAYER",
  SET_PLAYER_NAME: "SET_PLAYER_NAME",
  SET_PLAYER_AVATAR: "SET_PLAYER_AVATAR",
  SET_PLAYER_FLAG: "SET_PLAYER_FLAG",
  SET_PLAYER_WIN_COUNT: "SET_PLAYER_WIN_COUNT",
  SET_PLAYER_LOST_COUNT: "SET_PLAYER_LOST_COUNT",
  RESET_PLAYER: "RESET_PLAYER",

  SET_BOT: "SET_BOT",
  SET_BOT_NAME: "SET_BOT_NAME",
  SET_BOT_AVATAR: "SET_BOT_AVATAR",
  SET_BOT_FLAG: "SET_BOT_FLAG",
  SET_BOT_WIN_COUNT: "SET_BOT_WIN_COUNT",
  SET_BOT_LOST_COUNT: "SET_BOT_LOST_COUNT",
  RESET_BOT: "RESET_BOT",

  SET_PLAYER_BOARD: "SET_PLAYER_BOARD",
  UPDATE_PLAYER_BOARD: "UPDATE_PLAYER_BOARD",
  DELETE_PLAYER_BOARD: "DELETE_PLAYER_BOARD",

  SET_PLAYER_SHIPS: "SET_PLAYER_SHIPS",
  UPDATE_PLAYER_SHIPS: "UPDATE_PLAYER_SHIPS",
  DELETE_PLAYER_SHIPS: "DELETE_PLAYER_SHIPS",

  SET_BOT_BOARD: "SET_BOT_BOARD",
  UPDATE_BOT_BOARD: "UPDATE_BOT_BOARD",
  DELETE_BOT_BOARD: "DELETE_BOT_BOARD",

  SET_BOT_SHIPS: "SET_BOT_SHIPS",
  UPDATE_BOT_SHIPS: "UPDATE_BOT_SHIPS",
  DELETE_BOT_SHIPS: "DELETE_BOT_SHIPS",

  OPEN_DIALOG: "OPEN_DIALOG",
  CLOSE_DIALOG: "CLOSE_DIALOG",

  MUSIC_ON: "MUSIC_ON",
  MUSIC_OFF: "MUSIC_OFF",

  SOUND_ON: "SOUND_ON",
  SOUND_OFF: "SOUND_OFF",

  SET_LEVEL: "SET_LEVEL"
};

export default actionTypes;